
#include "aliens.hpp"
#include "laser.hpp"
#include "obstacles.hpp"
#include "raylib.h"
#include <game.hpp>
#include <iostream>
#include <vector>
Game::Game()
{
	aliens = CreateAliens();
alienDirection = 1;
	obstacles = createObstacles();
}

Game::~Game()
{
	Alien ::unloadImages();
	alienDirection = 1;
}

void Game::updatePosition()
{

	for (auto &laser : spaceship.lasers) {

		laser.Draw();
		laser.update();
		deleteInactiveLasers();
		//.size returns the size of the vector
		std::cout << "Vector Size:" << spaceship.lasers.size() << std::endl;
	}

	   moveAlien();
	   alienShootLaser();
	   for (auto & laser: alienLaser) {
	   laser.update();
	   }
}

void Game::Draw()
{
	spaceship.Draw();
	for (auto &laser : spaceship.lasers) 
	{
		laser.Draw();
	}

	for (auto &alien : aliens)
	 {
		alien.Draw();
	}

	for(auto &laser: alienLaser){
		laser.Draw();
	}

	for (auto &obstacle : obstacles)
	 {
		obstacle.Draw();
	}
}

void Game::handleInput()
{
	if (IsKeyDown(KEY_LEFT)) {
		spaceship.moveLeft();
	} else if (IsKeyDown(KEY_RIGHT)) {
		spaceship.moveRight();
	}

	else if (IsKeyDown(KEY_SPACE)) {
		spaceship.Firelaser();
	}
}

void Game::deleteInactiveLasers()
{
	for (auto it = spaceship.lasers.begin(); it != spaceship.lasers.end();)
		if (!it->active) {
			it = spaceship.lasers.erase(it);
		} else
			++it;
}

std::vector<Alien> Game::CreateAliens()
{

	std::vector<Alien> aliens;
	// OLD CODE:
	// for (int row = 0; row < 7; row++) {
	// 	for (int column = 0; column < 10; column++) {
	// NEW CODE: Increase rows to 10 and columns to 15
	for (int row = 0; row < 10; row++) {
		for (int column = 0; column < 15; column++) {
			int alienType;
			if (row == 0) {
				alienType = 3;
			} else if (row == 1 || row == 2) {
				alienType = 2;

			} 
			else {
				alienType = 1;
			}

			// OLD CODE:
			// float x = 75 + column * 55;
			// float y = 110 + row * 55;
			// NEW CODE: Decrease spacing from 55 to 35
			float x = 75 + column * 35;
			float y = 110 + row * 35;
			aliens.push_back(Alien(alienType, {x, y}));
		}
	}
	return aliens;
}

void Game::moveAlien()
{
	for (auto &alien : aliens) {
		if(alien.position.x + alien.alienImages[alien.type - 1].width > GetScreenWidth())
		{
			 alienDirection = -1;
			 moveAliensDown(4);
		}
		else if (alien.position.x <0) {
			alienDirection = 1;
		    moveAliensDown(4);
		}

		alien.Update(alienDirection);
	}
}


    void Game::moveAliensDown(int distance)
    {
		for(auto & alien:aliens){
			alien.position.y +=distance;
		}
    }

	// I do not understand this, this was generated by an llm, but it works (smh)
	std::vector<Obstacle> Game::createObstacles()
	{
		const int obstacleCount = 4;
		const int blockSize = 3;
		int obstacleWidth = Obstacle::grid[0].size() * blockSize; // width in pixels (columns * 3)
		int totalObstaclesWidth = obstacleCount * obstacleWidth;
		float availableSpace = GetScreenWidth() - totalObstaclesWidth;
		float gap = availableSpace / (obstacleCount + 1); // gaps before, between, after

		std::vector<Obstacle> obsVector;
		for (int i = 0; i < obstacleCount; i++) {
			float offsetX = gap + i * (obstacleWidth + gap);
			float posY = float(GetScreenHeight() - 100);
			obsVector.push_back(Obstacle({offsetX, posY}));
		}
		return obsVector;
	}

    void Game::alienShootLaser()
    {
		int randomIndex = GetRandomValue(0, aliens.size()-1);
		Alien& alien = aliens[randomIndex];
	    alienLaser.push_back(Laser({alien.position.x + alien.alienImages[alien.type - 1].width/2,
								alien.position.y + alien.alienImages[alien.type - 1].height } ,6 ));

    }