
#include "aliens.hpp"
#include "laser.hpp"
#include "obstacles.hpp"
#include "raylib.h"
#include <game.hpp>
#include <iostream>
#include <vector>
Game::Game()
{
	aliens = CreateAliens();
	alienDirection = 1;
	obstacles = createObstacles();

	// --- NEW SPACE INVADERS SETUP ---
	// Initialize movement timer. Starts off moving every half second.
	timeLastAlienMoved = GetTime();
	alienMoveInterval = 0.5;

	// Initialize shooting timer.
	timeLastAlienShot = GetTime();
	// Randomize the first shot between 1.0 and 3.0 seconds
	alienShootInterval = GetRandomValue(10, 30) / 10.0;
}

Game::~Game()
{
	Alien ::unloadImages();
	alienDirection = 1;
}

void Game::updatePosition()
{

	for (auto &laser : spaceship.lasers) {

		laser.Draw();
		laser.update();
		deleteInactiveLasers();
		//.size returns the size of the vector
		std::cout << "Vector Size:" << spaceship.lasers.size() << std::endl;
	}

	moveAlien();
	alienShootLaser();
	for (auto &laser : alienLaser) {
		laser.update();
	}
}

void Game::Draw()
{
	spaceship.Draw();
	for (auto &laser : spaceship.lasers) {
		laser.Draw();
	}

	for (auto &alien : aliens) {
		alien.Draw();
	}

	for (auto &laser : alienLaser) {
		laser.Draw();
	}

	for (auto &obstacle : obstacles) {
		obstacle.Draw();
	}
}

void Game::handleInput()
{
	if (IsKeyDown(KEY_LEFT)) {
		spaceship.moveLeft();
	} else if (IsKeyDown(KEY_RIGHT)) {
		spaceship.moveRight();
	}

	else if (IsKeyDown(KEY_SPACE)) {
		spaceship.Firelaser();
	}
}

void Game::deleteInactiveLasers()
{
	for (auto it = spaceship.lasers.begin(); it != spaceship.lasers.end();)
		if (!it->active) {
			it = spaceship.lasers.erase(it);
		} else
			++it;
}

std::vector<Alien> Game::CreateAliens()
{

	std::vector<Alien> aliens;
	// OLD CODE:
	// for (int row = 0; row < 7; row++) {
	// 	for (int column = 0; column < 10; column++) {
	// NEW CODE: Increase rows to 10 and columns to 15
	for (int row = 0; row < 10; row++) {
		for (int column = 0; column < 15; column++) {
			int alienType;
			if (row == 0) {
				alienType = 3;
			} else if (row == 1 || row == 2) {
				alienType = 2;

			} else {
				alienType = 1;
			}

			// OLD CODE:
			// float x = 75 + column * 55;
			// float y = 110 + row * 55;
			// NEW CODE: Decrease spacing from 55 to 35
			float x = 75 + column * 35;
			float y = 110 + row * 35;
			aliens.push_back(Alien(alienType, {x, y}));
		}
	}
	return aliens;
}

void Game::moveAlien()
{
	// NEW CODE: Space Invaders block movement logic
	// We only want the aliens to move if the specific interval has passed.
	if (GetTime() - timeLastAlienMoved >= alienMoveInterval) {
		// Reset the movement timer
		timeLastAlienMoved = GetTime();

		// Calculate the new speed interval based on how many aliens are left.
		// As aliens are destroyed, size decreases, so the interval becomes smaller (faster!).
		// E.g., 150 aliens * 0.003 = 0.45s. 1 alien * 0.003 = 0.003s.
		// We add a base 0.05 so they don't go infinitely fast.
		alienMoveInterval = (aliens.size() * 0.003) + 0.05;

		// Move all aliens horizontally by a "step" (e.g., 15 pixels)
		// alienDirection is still 1 (right) or -1 (left)
		int stepSize = 15;
		for (auto &alien : aliens) {
			alien.Update(alienDirection * stepSize);
		}

		// Now check if ANY alien in the grid has hit the screen edge
		bool hitEdge = false;
		for (auto &alien : aliens) {
			if (alien.position.x + alien.alienImages[alien.type - 1].width >= GetScreenWidth() ||
			    alien.position.x <= 0) {
				hitEdge = true;
				break; // Stop checking, we already know the block hit the edge
			}
		}

		// If the block hit the edge, we need to reverse direction and move them down
		if (hitEdge) {
			alienDirection *= -1; // Flip horizontal direction
			moveAliensDown(15);   // Move the block down by 15 pixels

			// Step the aliens back away from the edge so they don't get stuck
			// triggering the collision over and over again on the next frame
			for (auto &alien : aliens) {
				alien.Update(alienDirection * stepSize);
			}
		}
	}
}

void Game::moveAliensDown(int distance)
{
	for (auto &alien : aliens) {
		alien.position.y += distance;
	}
}

// I do not understand this, this was generated by an llm, but it works (smh)
std::vector<Obstacle> Game::createObstacles()
{
	const int obstacleCount = 4;
	const int blockSize = 3;
	int obstacleWidth = Obstacle::grid[0].size() * blockSize; // width in pixels (columns * 3)
	int totalObstaclesWidth = obstacleCount * obstacleWidth;
	float availableSpace = GetScreenWidth() - totalObstaclesWidth;
	float gap = availableSpace / (obstacleCount + 1); // gaps before, between, after

	std::vector<Obstacle> obsVector;
	for (int i = 0; i < obstacleCount; i++) {
		float offsetX = gap + i * (obstacleWidth + gap);
		float posY = float(GetScreenHeight() - 100);
		obsVector.push_back(Obstacle({offsetX, posY}));
	}
	return obsVector;
}

void Game::alienShootLaser()
{
	// NEW CODE: Shoot on a timer, not every single frame!
	// We also check !aliens.empty() to prevent crashing if all aliens are dead
	if (GetTime() - timeLastAlienShot >= alienShootInterval && !aliens.empty()) {
		// Reset timer
		timeLastAlienShot = GetTime();

		// Randomize the interval for the next shot (between 0.5 and 2.5 seconds)
		// This makes the alien fire rate unpredictable like the arcade game
		alienShootInterval = GetRandomValue(1, 6) / 10.0;

		// Pick a random alien to shoot
		int randomIndex = GetRandomValue(0, aliens.size() - 1);
		Alien &alien = aliens[randomIndex];

		// Fire laser from the center bottom of that alien
		alienLaser.push_back(Laser({alien.position.x + alien.alienImages[alien.type - 1].width / 2,
		                            alien.position.y + alien.alienImages[alien.type - 1].height},
		                           6));
	}
}