
#include "laser.hpp"
#include "obstacles.hpp"
#include "raylib.h"
#include <game.hpp>
#include <iostream>
#include <vector>
Game::Game()
{
	obstacles = createObstacles();
}

Game::~Game()
{
}

void Game::updatePosition()
{

	for (auto &laser : spaceship.lasers) {

		laser.Draw();
		laser.update();
		deleteInactiveLasers();
		//.size returns the size of the vector
		std::cout << "Vector Size:" << spaceship.lasers.size() << std::endl;
	}
}

void Game::Draw()
{
	spaceship.Draw();
	for (auto &laser : spaceship.lasers) {

		laser.Draw();
	}
	for (auto &obstacle : obstacles) {
		obstacle.Draw();
	}
}

void Game::handleInput()
{
	if (IsKeyDown(KEY_LEFT)) {
		spaceship.moveLeft();
	} else if (IsKeyDown(KEY_RIGHT)) {
		spaceship.moveRight();
	}

	else if (IsKeyDown(KEY_SPACE)) {
		spaceship.Firelaser();
	}
}

void Game::deleteInactiveLasers()
{
	for (auto it = spaceship.lasers.begin(); it != spaceship.lasers.end();)
		if (!it->active) {
			it = spaceship.lasers.erase(it);
		} else
			++it;
}
// I do not understand this, this was generated by an llm, but it works (smh)
std::vector<Obstacle> Game::createObstacles()
{
	const int obstacleCount = 4;
	const int blockSize = 3;
	int obstacleWidth = Obstacle::grid[0].size() * blockSize; // width in pixels (columns * 3)
	int totalObstaclesWidth = obstacleCount * obstacleWidth;
	float availableSpace = GetScreenWidth() - totalObstaclesWidth;
	float gap = availableSpace / (obstacleCount + 1); // gaps before, between, after

	std::vector<Obstacle> obsVector;
	for (int i = 0; i < obstacleCount; i++) {
		float offsetX = gap + i * (obstacleWidth + gap);
		float posY = float(GetScreenHeight() - 100);
		obsVector.push_back(Obstacle({offsetX, posY}));
	}
	return obsVector;
}